services:
  - type: web
    name: my-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python tg.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
